### ISSUE TITLE
I have the error No such file or directory when launching a connection with redpwn 

### ISSUE THREAD

**Issue by C0d1ac** [redpwn/jail#25]
I have a jail using python 
```python
#!/usr/local/bin/python

import random, time

x = random.randint(80, 120)

random.seed(time.time())

ll = [random.randrange(0,4294967294) for _ in range(624)]

togive = {"given":ll}

print(togive)
```

and this is the Dockerfile
```
FROM python:slim AS app
RUN pip install --no-cache-dir randcrack

FROM pwn.red/jail
COPY --from=app / /srv

ENV JAIL_POW=0 JAIL_PORT=1337 JAIL_TIME=20

COPY app.py /srv/app/run

WORKDIR /srv/app

RUN chmod +x run
```
and this is the compose file
```
version: '3.7'

services:
  predict:
    container_name: PyREDICTOR
    restart: unless-stopped
    build:
      context: ./challenge
      dockerfile: Dockerfile
    ports:
      - "5000:1337"
    privileged: true 
```
but i have this error when launching a connection 
```
PyREDICTOR  | [I][2024-05-11T12:50:57+0000] Setting 'cpu.max' to '100000 1000000'
PyREDICTOR  | [I][2024-05-11T12:50:57+0000] Executing '/app/run' for '[::ffff:172.19.0.1]:42914'
PyREDICTOR  | [E][2024-05-11T12:50:57+0000][1] newProc():225 execve('/app/run') failed: No such file or directory
PyREDICTOR  | [F][2024-05-11T12:50:57+0000][1] runChild():483 Launching child process failed
PyREDICTOR  | [W][2024-05-11T12:50:57+0000][1] runChild():503 Received error message from the child process before it has been executed
PyREDICTOR  | [I][2024-05-11T12:50:57+0000] pid=12 ([::ffff:172.19.0.1]:42914) exited with status: 255, (PIDs left: 0)
```
